//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mejiaaguilar_20211020.SQL.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class mejiaaguilar_20211020Entities : DbContext
    {
        public mejiaaguilar_20211020Entities()
            : base("name=mejiaaguilar_20211020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
    
        [DbFunction("mejiaaguilar_20211020Entities", "fnPager")]
        public virtual IQueryable<fnPager_Result> fnPager(Nullable<int> page, Nullable<int> cantReg)
        {
            var pageParameter = page.HasValue ?
                new ObjectParameter("page", page) :
                new ObjectParameter("page", typeof(int));
    
            var cantRegParameter = cantReg.HasValue ?
                new ObjectParameter("cantReg", cantReg) :
                new ObjectParameter("cantReg", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPager_Result>("[mejiaaguilar_20211020Entities].[fnPager](@page, @cantReg)", pageParameter, cantRegParameter);
        }
    }
}
